plugins {
    kotlin("jvm") version "2.0.0"
    id("org.jetbrains.kotlinx.atomicfu") version "0.25.0"
}

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.8/samples
 */
dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0-RC")

    // Dependencies required by "lincheck-jvm-2.34-snapshot" JAR file
    implementation("org.jetbrains.kotlin:kotlin-reflect:2.0.20")
    implementation("net.bytebuddy:byte-buddy-agent:1.15.1")
    implementation("org.ow2.asm:asm:9.3")
    implementation("org.ow2.asm:asm-util:9.4")

    testImplementation("junit:junit:4.13.1")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0-RC")

    // Dependencies required by "lincheck-jvm-2.34-snapshot" JAR file
    testImplementation(files("$rootDir/build/libs/lincheck-jvm-2.34-snapshot.jar"))
    testImplementation("org.ow2.asm:asm-commons:9.7")
}

repositories {
    mavenCentral()
}