name: Run Gradle tests

# Run tests when `push` is performed or when it is a PR targeting 'main'
on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    needs: build-gradle-project
    steps:
      - name: Build Gradle project
        uses: actions/build-gradle-project
      - name: Run tests for a rendezvous channel
        run: ./gradlew test --tests "RendezvousChannelTest"

